### ISSUE TITLE
DelphiAST does not support complex compiler directives

### ISSUE THREAD

**Issue by RomanYankovsky** [RomanYankovsky/DelphiAST#20]
DelphiAST works fine with simple compiler directives like {$IFDEF A} or {$IF DEFINED(A)}, but does not support complex compiler directives like {$IF DEFINED(A) AND NOT DEFINED(B)}.

**Comment by LaKraven** [comment]
The following is also not supported: {$IF SOME_CONSTANT >= SOME_INTEGER}

The code responsible for handling "Conditional Expressions" resides in SimplerParser.Lexer.pas between lines 1505 and 1521.

I believe it shouldn't be too difficult to introduce additional conditions within that block of code to handle other more advanced "Conditional Expressions" and am taking a look at this right now.

**Comment by LaKraven** [comment]
Re my last comment, I suggest we make "complex Conditional Expression evaluation" a separate issue as this would be best implemented AFTER resolving issue #30.

A working solution to the original context specific in this issue has been committed to my fork, and a pull request issued. It has been tested with every combination of expression, and appears to work very well indeed.

**Comment by RomanYankovsky** [comment]
Now it's much better! But we also have to remember that brackets is also not supported yet. Like:
```delphi
{$IF DEFINED(A) AND (DEFINED(B) OR DEFINED(C))}
```
I'll create a new issue later to better describe the current state.

**Comment by LaKraven** [comment]
I did think about that before I implemented my intermediary solution.

The only thing there is I'd have to define and build an "expression tree" before evaluating it. It's not exactly the most difficult thing in the world, and I'm going to get that done hopefully this coming weekend when I have some time free.

The reason I did the intermediary solution is that certain units in a particular codebase were using multiple conditional expressions and wouldn't parse. Thus far, I haven't encountered any "conditional expression trees" in our codebase, so I didn't put the extra time in (at this point).

Beauty of outsourcing the solution into its own method (rather than all rolled into that massive CASE OF statement) is that we need only implement it once, and it applies to both {$IF} and {$ELSEIF} statements identically.
