### ISSUE TITLE
Provide an interface to support $INCLUDE compiler directive in parser

### ISSUE THREAD

**Issue by RomanYankovsky** [RomanYankovsky/DelphiAST#54]
DelphiAST is able to process {$INCLIDE ...} directive, but it does not have any handler at this moment.

**Comment by Wosi** [comment]
I added a handler for include directives in my fork at https://github.com/Wosi/DelphiAST/

How it works:
TmwBasePasLex can hold a member of the new interface type IIncludeHandler. When it is assigned it receives the name of the include file and should return the content of the file as string. A dummy implementation is provided in the demo project. The file content will be pasted at the start position of the include directive into the FOrigin string. The included content is going to be parsed like it has always been part of the original file. This way there is no need to start parsing the file again from the beginning. Nested includes are supported, too. SyntaxNodes that come into the file via include have a position of -1,-1. All other nodes will keep their original file position.

Since the original file content is hold as a PChar and there might be several pointers to different positions of the string it's not possible to create a new string at a new memory position during the include. That's why I need to alloc additional memory when SetOrigin is being called. Right now I reserve 1MiB for includes and need to free it manually when parsing is done.

You can pull it via the FPC support pull request.

**Comment by RomanYankovsky** [comment]
@Wosi thanks, this is great :)
I have merged the pull request and created a unit test for this functionality.

**Comment by Wosi** [comment]
Thanks. I made a shameful mistake regarding the memory management. That mistakes leads to access violations when includes are handled in very huge .pas files (like [this one](https://raw.githubusercontent.com/project-jedi/jcl/master/jcl/source/windows/mscorlib_TLB.pas)). 
I strongly recommend you to cherry-pick my commit 1bed41b8e84890667eebb872ca33afd82a2db2c5. It fixes this bug. Sorry for this mistake. 

I also recommend you to cherry-pick cabbc17984a02cdda25094bab8d22f1da2d9bbd0 in order to be able to compile the demo project with Lazarus again.

**Comment by RomanYankovsky** [comment]
Could you please create a pull request?
