### ISSUE TITLE
Syntax node names: replacing strings with enums

### ISSUE THREAD

**Issue by RomanYankovsky** [RomanYankovsky/DelphiAST#69]
I'm going to refactor TSyntaxNode changing Name field type from string to enumerated type. This will reduce memory consumption. And _may_ also improve performance a little bit.

Discuss :)

**Comment by LaKraven** [comment]
Completely agree with this!

Improves efficiency (and readability) of any method contingent on the Name field because you will be able to use a simple `Case Of` expression.

Also improves performance because it reduces the mem alloc ops (will likely be imperceptible on small-scale projects, but that time will add up on more *larger-scale* implementations)

**Comment by polyaklaci** [comment]
I also agree. I see the benefits as LaKraven, plus all the used AST node names will be in one exact 'definition group'. Enumeration names also can be used for the generation of the XML node name strings (with "GetEnumName")... 
If you make some refactoring in the project, you may change some things to make your classes (TPasSyntaxTreeBuilder, etc.) 'inheritable' (make the methods 'virtual' and change some private member to protected level).
This will be useful to me, because when I modify something in the DelphiAST code, I don't change the 'original' code, but inherit a new class from it (in a separate unit), and I make the changes on it. So this way the 'pending' modifications is 'collected' in my inherited class (and the original code is 'replaceable' to a new version anytime). To work this way, now I has to use ugly 'class helpers' to access private members (which is a hack). If you make the DelphiAST classes 'inheritable', it can be much simpler and cleaner...

**Comment by RomanYankovsky** [comment]
@polyaklaci do you mean you want to make FStack field protected, but not private? Ok, I'll move it.

**Comment by sglienke** [comment]
@RomanYankovsky I guess making a protected readonly Stack property will be sufficient.

**Comment by RomanYankovsky** [comment]
Refactoring is finished. I've made my changes in the new branch called StringsToEnums: 39250e38a69346fc9388e1debdffe208d0d2770f

I will merge it with master when I believe that these changes do not break something :)
